import { copyFile, mkdir, readFile, rm, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import { spawnSync } from 'node:child_process';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const require = createRequire(import.meta.url);
const legacyVendor = path.join(root, 'assets', 'vendor');
const runtimeCssPath = path.join(root, 'assets', 'css', 'runtime.css');
const phaserPath = path.join(root, 'assets', 'js', 'phaser.min.js');
const tempDir = path.join(root, '.partyjniak-build');
const tailwindPath = path.join(tempDir, 'tailwind.css');

function asDataUri(buffer, mime) {
  return `data:${mime};base64,${buffer.toString('base64')}`;
}

async function inlineInterFonts(css, interRoot) {
  let output = css.replace(/,\s*url\(\.\/files\/[^)]+\.woff\)\s*format\('woff'\)/g, '');
  const files = [...new Set([...output.matchAll(/url\(\.\/files\/([^)]+\.woff2)\)/g)].map(match => match[1]))];

  for (const file of files) {
    const data = await readFile(path.join(interRoot, 'files', file));
    output = output.replaceAll(`url(./files/${file})`, `url(${asDataUri(data, 'font/woff2')})`);
  }
  return output;
}

async function inlineFontAwesomeFonts(css, fontAwesomeRoot) {
  let output = css.replace(/,url\(\.\.\/webfonts\/[^)]+\.ttf\) format\("truetype"\)/g, '');
  const files = [...new Set([...output.matchAll(/url\(\.\.\/webfonts\/([^)]+\.woff2)\)/g)].map(match => match[1]))];

  for (const file of files) {
    const data = await readFile(path.join(fontAwesomeRoot, 'webfonts', file));
    output = output.replaceAll(`url(../webfonts/${file})`, `url(${asDataUri(data, 'font/woff2')})`);
  }
  return output;
}

await rm(legacyVendor, { recursive: true, force: true });
await rm(tempDir, { recursive: true, force: true });
await mkdir(tempDir, { recursive: true });
await mkdir(path.dirname(runtimeCssPath), { recursive: true });
await mkdir(path.dirname(phaserPath), { recursive: true });

await copyFile(
  path.join(root, 'node_modules', 'phaser', 'dist', 'phaser.min.js'),
  phaserPath
);

const fontAwesomeRoot = path.join(root, 'node_modules', '@fortawesome', 'fontawesome-free');
const interRoot = path.join(root, 'node_modules', '@fontsource', 'inter');

const interSource = await readFile(path.join(interRoot, 'latin.css'), 'utf8');
const fontAwesomeSource = await readFile(path.join(fontAwesomeRoot, 'css', 'all.min.css'), 'utf8');
const interCss = await inlineInterFonts(interSource, interRoot);
const fontAwesomeCss = await inlineFontAwesomeFonts(fontAwesomeSource, fontAwesomeRoot);

const tailwindCli = require.resolve('tailwindcss/lib/cli.js');
const tailwindResult = spawnSync(process.execPath, [
  tailwindCli,
  '-c', path.join(root, 'tailwind.config.cjs'),
  '-i', path.join(root, 'assets', 'css', 'tailwind-input.css'),
  '-o', tailwindPath,
  '--minify'
], { cwd: root, stdio: 'inherit' });

if (tailwindResult.status !== 0) throw new Error('Nie udało się zbudować lokalnego Tailwinda.');

const tailwindCss = await readFile(tailwindPath, 'utf8');
const runtimeCss = [
  '/* Generated by scripts/build-assets.mjs. Do not edit. */',
  ':root{--partyjniak-runtime-bundle:ready}',
  interCss,
  fontAwesomeCss,
  tailwindCss
].join('\n');

await writeFile(runtimeCssPath, runtimeCss, 'utf8');
await mkdir(legacyVendor, { recursive: true });
await writeFile(
  path.join(legacyVendor, 'precache.json'),
  `${JSON.stringify(['./assets/css/runtime.css', './assets/js/phaser.min.js'], null, 2)}\n`,
  'utf8'
);
await rm(tempDir, { recursive: true, force: true });

console.log(`Built self-contained runtime CSS (${runtimeCss.length} bytes), local Phaser, and a PWA-only precache manifest.`);
